/*
 * SQL runner audit report generator. Run with: npx vite-node scripts/sql-audit.mts
 *
 * Boots the same seeded PGlite sandbox the app uses, runs every executable gold solution, and
 * writes a per-problem inventory to docs/sql-runner-audit.md. Lives outside tsconfig `include`
 * (only src/tests are typechecked) so it may use node:fs without @types/node.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { runSql, REFERENCE_NOW } from '@/sqlRunner';
import { problemRunnable, exerciseRunnable, statusForId, overrideReason } from '@/sqlRunner/executable';
import { PROBLEMS } from '@/data/gym';
import { MODULES } from '@/data/modules';

type Row = { id: string; source: string; tables: string; status: string; runs: boolean; rows: number; cols: string; note: string };

const audit: Row[] = [];

async function record(displayId: string, statusId: string, source: string, tables: string, solution: string, runnable: boolean) {
  if (!runnable) {
    audit.push({ id: displayId, source, tables, status: statusForId(statusId), runs: false, rows: 0, cols: '', note: overrideReason(statusId) ?? 'not executable' });
    return;
  }
  const r = await runSql(solution);
  audit.push({ id: displayId, source, tables, status: 'ready', runs: r.ok, rows: r.rowCount, cols: r.columns.join(' '), note: r.ok ? '' : r.error ?? 'error' });
}

for (const p of PROBLEMS as Array<{ id: string; mode?: string; ladder?: string; solution?: string; schema?: string[] }>) {
  if (p.mode !== 'SQL' || !p.solution) continue;
  await record(p.id, p.id, `gym:${p.ladder}`, (p.schema ?? []).join(', '), p.solution, problemRunnable(p));
}
for (const m of MODULES as Array<{ id: string; sqlPattern?: string; schemaRefs?: string[]; exercises: Array<{ id: string; solution?: string }> }>) {
  if (!m.sqlPattern) continue;
  for (const ex of m.exercises) {
    if (!ex.solution) continue;
    await record(`${m.id}/${ex.id}`, ex.id, `module:${m.id}`, (m.schemaRefs ?? []).join(', '), ex.solution, exerciseRunnable(true, ex));
  }
}

const ready = audit.filter((a) => a.status === 'ready');
const nonExec = audit.filter((a) => a.status !== 'ready');
const passing = ready.filter((a) => a.runs);

const md = [
  '# SQL runner audit report',
  '',
  '_Generated by `npx vite-node scripts/sql-audit.mts`. Do not edit by hand._',
  '',
  `- Reference instant (frozen \`now()\`): \`${REFERENCE_NOW}\``,
  `- Executable SQL gold solutions audited: **${ready.length}**`,
  `- Passing against the seed: **${passing.length}**`,
  `- Non-executable (Run button hidden): **${nonExec.length}**`,
  '',
  '## Executable problems',
  '',
  '| id | source | required tables | runs | rows | columns |',
  '|---|---|---|---|---|---|',
  ...ready.map((a) => `| ${a.id} | ${a.source} | ${a.tables} | ${a.runs ? '✅' : '❌'} | ${a.rows} | ${a.cols} |`),
  '',
  '## Non-executable problems (Run button hidden)',
  '',
  '| id | source | status | reason |',
  '|---|---|---|---|',
  ...nonExec.map((a) => `| ${a.id} | ${a.source} | ${a.status} | ${a.note} |`),
  '',
].join('\n');

mkdirSync('docs', { recursive: true });
writeFileSync('docs/sql-runner-audit.md', md);
console.log(`Wrote docs/sql-runner-audit.md — ${ready.length} executable, ${passing.length} passing, ${nonExec.length} non-executable.`);
const failed = ready.filter((a) => !a.runs);
if (failed.length) {
  console.error('FAILED gold solutions:\n' + failed.map((a) => `  ${a.id}: ${a.note}`).join('\n'));
  process.exit(1);
}
